### ISSUE TITLE
Bad Request: wrong chat id

### ISSUE THREAD

**Issue by iMoein** [jaavid/jadibot#2]
سلام
مرسی از سورس کدی که قرار دادید.
من برای آزمایش سورس رو روی سرورم نصب کردم و بعد از ساخت بانک و باقی کارهایی که به نظرم میرسید تونستم به صورت دستی با وارد کردن  آی دی متغیرها خروجی به تلگرام بفرستم. اما یک سوال دارم ازتون و اون هم این هست که چرا اطلاعات و فرامین کاربرها رو به صورت خودکارریتریو نمیکنه و پیام 
Code: 400. Description: "Error: Bad Request: wrong chat id". 
رو بهم نشون میده؟

**Comment by jaavid** [comment]
سلام
خواهش میکنم
این کدها رو باید روی سرور قرار بدید و آدرس رو به عنوان [وب هوک](https://core.telegram.org/bots/api#setwebhook) برای تلگرام معرفی کنید.
بعد هر بار که به روبات شما پیغامی فرستاده میشه، تلگرام پیغام رو به این اسکریپت میفرسته و اسکریپت پیغام رو پردازش میکنه و جواب مناسب ارسال میکنه.

**Comment by iMoein** [comment]
موضوع این هست که من وب هوک رو هم معرفی کردم ولی هیچ ری اکشنی ازش نمیگیرم، به نظرتون مشکل از کجا میتونه باشه؟
ممکنه از گواهینامه SSL ای باشه که روی دامین دارم؟

**Comment by jaavid** [comment]
شاید
چون تلگرام گفته که حتما باید از اس‌اس‌ال های معتبر استفاده کنید.

**Comment by iMoein** [comment]
مرسی از راهنماییتون
